### ISSUE TITLE
Rassembler les infos spécifiques dans un/des fichiers de configs

### ISSUE THREAD

**Issue by tuxayo** [papjul/PlanningIUTInfo#7]
Objectif: même base de code pour les instances de l'IUT et de L3 infos par exemple

**Comment by papjul** [comment]
Est-ce que l’issue #10 serait une solution à ton problème ?

**Comment by tuxayo** [comment]
Les deux ne sont pas mutuellement exclusives. Mais c'est sûr que #10 et moins coûteuse et peut régler #7 de façon satisfaisante.
